### ISSUE TITLE
PubMLST Export for Haemophilus

### ISSUE THREAD

**Issue by markusrt** [markusrt/NRZMHiDB#45]
Similar to laboratory export a PubMLST Excel export should be implemented.

Filter should allow to select
- Period (from-to date)
- adjusted/unadjusted (Bereinigt, Unbereinigt)
   Adjusted records: Only blood or liquor, German residence, no duplicates
   Unadjusted records: Everything from given period

See attached excel for definition/hints on export columns:
[upload_template.xlsx](https://github.com/markusrt/NRZMHiDB/files/4715355/upload_template.xlsx)

**Comment by markusrt** [comment]
Why are these two columns to be left empty?
![image](https://user-images.githubusercontent.com/299753/84604503-cdd77b80-ae96-11ea-9e1a-f26000f2c33a.png)

Opposed to 
![image](https://user-images.githubusercontent.com/299753/84604517-e778c300-ae96-11ea-977c-a1f068020312.png)

**Comment by thien-tri** [comment]
amx is to be left empty, amc_mic is to be filled if data exist, otherwise left empty.
explanation: amx is never measured. however, susceptibility interpretation (amx_SIR) can be inferred from ampicillin susceptibility. amc mic is not measured systematically. however, if this is done, the values can be indicated and an interpretation can be provided.
The form does not allow the values "intersx" or "n.a.". In these cases "sex" should be left blank.

**Comment by markusrt** [comment]
@thien-tri continuing working on the export I found some other missing definitions

**Evaluation**, i.e. PubMLST "serotype"
which of the allowed values of "ND", "NT", "non-b" should the following evaluations be mapped to?
Or should these stay empty?
```
Evaluation.HaemophilusHemolyticus
Evaluation.HaemophilusParainfluenzae
Evaluation.NoGrowth
Evaluation.NoHaemophilusSpecies
Evaluation.HaemophilusInfluenzae
Evaluation.HaemophilusSpeciesNoHaemophilusInfluenzae
Evaluation.NoHaemophilusInfluenzae
```

**Agglutination**, i.e. PubMLST "serotype_by_serology"
which of the allowed values of "NT", "non-b" should the following agglutinations be mapped to?
Or should these stay empty?
```
SerotypeAgg.Negative
SerotypeAgg.Auto
SerotypeAgg.Poly
SerotypeAgg.NotEvaluable
```

**SerogroupPcr**, i.e. PubMLST "serotype_by_PCR"
which of the allowed values of "NT", "non-b" should `SerotypePcr.Negative` be mapped to?
Or should these stay empty?

**Comment by thien-tri** [comment]
Evaluation. VERY IMPORTANT! If Haemophilus influenzae, then indicate ND. If one of the following:
Evaluation.HaemophilusParainfluenzae
Evaluation.NoGrowth
Evaluation.NoHaemophilusSpecies
Evaluation.HaemophilusSpeciesNoHaemophilusInfluenzae
Evaluation.NoHaemophilusInfluenzae
then the whole data set for this submission should be deleted from the export. We only want to export haemophilus influenzae from blood and/or csf!

Agglutination. If SerotypeAgg.NotEvaluable, then leave empty.  If one of the following:
SerotypeAgg.Negative
SerotypeAgg.Auto
SerotypeAgg.Poly
then indicate NT.

SerogroupPcr. If SerotypePcr.Negative then indicate NT.

ftsI. The entry in the first field (one single numeric value) should be indicated.

**Comment by markusrt** [comment]
> If one of the following:
> Evaluation.HaemophilusParainfluenzae
> Evaluation.NoGrowth
> Evaluation.NoHaemophilusSpecies
> Evaluation.HaemophilusSpeciesNoHaemophilusInfluenzae
> Evaluation.NoHaemophilusInfluenzae
> then the whole data set for this submission should be deleted from the export. We only want to export haemophilus influenzae from blood and/or csf!

@thien-tri Thanks for clarification. Now it seems that "the whole data for this submission should be deleted" is conflicting with the initial requirement to allow to export "Adjusted" and "Unadjusted" (see description on top)

Or does this still apply only that above mentioned evaluations are _always excluded_.

**Comment by thien-tri** [comment]
ftsI: the numeric field is the correct one (so if it is the 3rd field, then use this one).

You are right. I needed to give your objection some thought, and I ultimately think that pubMLST is highly species-specific. So organisms other than H. influenzae should be deleted from the export, even it is unadjusted.

**Comment by thien-tri** [comment]
Clarification to the export function:
IRIS export does not differ from PubMLST export, even though it will be submitted to a different different data base. The data format is entirely based on the PubMLST format.

Duplicates:
A duplicate is assumed if two (or more) strains from the same patient are submitted to the NRZMHi. This redundancy should be avoided. Therefore, the dataset with the earliest "date sampled" should be kept, identical subsequent submissions should be eliminated. Since we do not have the name of the patient, he/she would have to be identified by the identity of all of the following parameters:
patient parameters:
- initials
- date of birth
- sex
- postal code

strain parameters:
- source
- serotype
- beta-lactamase
- AMX_SIR

exceptions:
(1) if all patient parameters are identical, but at least one of the strain parameters differes, then indicate both submissions, but mark them for user control (e.g. by color?)
explanation: the same patient may be infected by two different strains or a mistake was made during user entry of isolate data
(2) if all patient parameters are identical, but all strain parameters are blank in one submission, then eliminate the complete submission with blank parameters
explanation: in case there was no growth, we aks the laboratory to resubmit the strain. Usually, the strain can be cultivated and analysed upon resubmission. Since all our submissions are documented, these cases create duplicate datasets for the same strain (the first one with no results, the second one with valid results).
(3) if all parameters are identical, but date sampled are more than 6 months apart, then indicate both submissions, but mark them for user control (e.g. by color?)
explanation: the same person may be reinfected by the same disease multiple times. From our data, we cannot know if this is the case, if we receive multiple submissions from one person. However, it can be assumed that two submissions more than 6 months apart derive from different disease events.

**Comment by markusrt** [comment]
@thien-tri Changes to export are now available on Test-System.

Duplicates are marked with a special column:
![image](https://user-images.githubusercontent.com/299753/86563237-4eecd480-bf64-11ea-9f65-04476e9f060c.png)

Please let me know if everything works as expected. Then I would deploy the export to production this evening.

**Comment by thien-tri** [comment]
This is perfect. I have looked at the export function on the test-system. I looks just fine. Thank you very much for your help.
